let csrf='';const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),notify=(message,error=false)=>{let t=$('#toast');t.textContent=message;t.className=error?'show error':'show';setTimeout(()=>t.className='',4000)},api=async(u,o={})=>{o.headers={...(o.headers||{})};if(o.method&&!['GET','HEAD'].includes(o.method))o.headers['X-CSRF-Token']=csrf;let r=await fetch(u,o);if(r.status===401){$('#loginModal').showModal();throw Error('Sign in required')}let d=await r.json().catch(()=>({detail:'Request failed'}));if(!r.ok)throw Error(d.detail||'Request failed');return d},json=(method,body)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
$('#menu').onclick=()=>$('#nav').classList.toggle('open');document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));$('#filterToggle').onclick=()=>$('#filters').classList.toggle('open');document.querySelectorAll('.close').forEach(x=>x.onclick=()=>x.closest('dialog').close());
const metrics={jobs_found:'Jobs discovered',high_match:'High matches',prepared:'Prepared',submitted:'Submitted',needs_input:'Needs input',interviews:'Interviews',rejected:'Rejected',awaiting_response:'Awaiting response',runs_today:'Runs today',last_run:'Last run'};
async function load(){let m=await api('/api/overview');$('#metrics').innerHTML=Object.entries(metrics).map(([k,v])=>`<div class=metric><b>${esc(m[k]||0)}</b><span>${v}</span></div>`).join('');let jobs=await api(`/api/jobs?q=${encodeURIComponent($('#search').value)}&status=${encodeURIComponent($('#status').value)}`);$('#empty').hidden=jobs.length;$('#jobcards').innerHTML=jobs.map(j=>`<article class=card><div class=cardtop><div class=score>${Math.round(j.score||0)}</div><div><div class=title>${esc(j.title)}</div><div class=sub>${esc(j.company)} · ${esc(j.location||'Location unstated')}</div></div></div><span class=pill>${esc(j.status)}</span><button onclick="detail(${j.id})">Review</button></article>`).join('');let apps=await api('/api/applications'),docs=await api('/api/documents');$('#applicationList').innerHTML=apps.length?apps.map(a=>`<p><b>${esc(a.title)}</b> · ${esc(a.company)}<br><small>${esc(a.status)} · ${esc(a.application_date)}</small></p>`).join(''):'<p>No applications tracked yet.</p>';$('#documentList').innerHTML=docs.length?docs.map(d=>`<p><b>${esc(d.document_type)}</b><br><small>${esc(d.local_path)} · ${esc(d.created_at)}</small><br><a href="/api/documents/${d.id}/download">Download securely</a></p>`).join(''):'<p>No generated documents yet.</p>';let messages=await api('/api/gmail/messages');$('#inboxList').innerHTML=messages.length?messages.map(m=>`<p><b>${esc(m.subject)}</b><br><small>${esc(m.sender)} · ${esc(m.classification)} · confidence ${Math.round((m.confidence||0)*100)}% · ${esc(m.response_status)}</small></p>`).join(''):'<p>No employment messages synced.</p>';let g=await api('/api/google/status');$('#googleState').innerHTML=`<p><b>${esc(g.status)}</b></p><small>Scopes: ${esc((g.scopes||[]).join(', ')||'none')}</small>`;let sources=await api('/api/sources');$('#sourceList').innerHTML=sources.map(s=>`<p><b>${esc(s.source_name)}</b> · ${esc(s.status)}<br><small>Search ${s.search_supported?'supported':'unavailable'} · Applications ${s.application_supported?'supported':'assisted/manual'}</small></p>`).join('');let c=await api('/api/config');$('#scheduleList').textContent=(c.preferences.schedule_times||[]).join(' · ');let logs=await api('/api/logs');$('#logLines').textContent=logs.lines.join('\n')||'No logs yet.'}
async function detail(id){let j=await api('/api/jobs/'+id);$('#detail').innerHTML=`<p class=eyebrow>MATCH SCORE ${esc(j.score||0)}</p><h2>${esc(j.title)}</h2><p>${esc(j.company)} · ${esc(j.location)}</p><h3>Why it matches</h3><p>${esc(j.reasoning)}</p><h3>Missing requirements / concerns</h3><p>${esc(j.missing_requirements)}</p><h3>Description</h3><div class=description>${esc(j.description)}</div><div class=actions><button onclick="action(${id},'cv')">Generate CV</button><button onclick="action(${id},'cover-letter')">Cover letter</button><button onclick="action(${id},'prepare')">Prepare application</button><button onclick="setStatus(${id},'APPLIED')">Mark applied</button><button onclick="window.open('${esc(j.application_url||j.vacancy_url)}','_blank','noopener')">Open application</button></div>`;$('#detailModal').showModal()}
async function action(id,name){try{await api(`/api/jobs/${id}/${name}`,{method:'POST'});await detail(id);load()}catch(e){notify(e.message,true)}}async function setStatus(id,status){await api(`/api/jobs/${id}/status`,json('POST',{status}));await detail(id);load()}
$('#run').onclick=async()=>{await api('/api/runs',{method:'POST'});$('#progress').classList.remove('hidden');poll()};async function poll(){let r=await api('/api/runs/latest');$('#runmsg').textContent=r.message;$('#runstate').textContent=r.state;if(r.state==='RUNNING')setTimeout(poll,1200);else{setTimeout(()=>$('#progress').classList.add('hidden'),2500);load()}}
$('#search').oninput=load;$('#status').onchange=load;$('#connectGoogle').onclick=async()=>{try{let r=await api('/api/google/connect',json('POST',{features:['gmail','drive','calendar']}));location.href=r.authorization_url}catch(e){notify(e.message,true)}};$('#refreshInbox').onclick=$('#syncGmail').onclick=async()=>{try{let r=await api('/api/gmail/sync',{method:'POST'});notify(`${r.messages_saved} job-related messages saved`);load()}catch(e){notify(e.message,true)}};$('#disconnectGoogle').onclick=async()=>{if(confirm('Remove the local Google token?')){await api('/api/google',{method:'DELETE'});load()}};
$('#setup').onclick=async()=>{let c=await api('/api/config'),f=$('#form'),p=c.profile,s=c.preferences;for(let n of ['name','email','phone','location','work_authorization'])if(f[n])f[n].value=p[n]||'';f.skills.value=(p.skills||[]).join(', ');f.categories.value=(s.job_categories||[]).join(', ');f.locations.value=(s.priority_locations||[]).join(', ');f.salary.value=p.salary_expectations||'';f.score.value=s.minimum_score||75;f.schedule.value=(s.schedule_times||[]).join(', ');f.feeds.value=(s.search_feeds||[]).join('\n');f.career_pages.value=(s.career_pages||[]).join('\n');f.greenhouse.value=(s.greenhouse_boards||[]).join(', ');f.lever.value=(s.lever_sites||[]).join(', ');f.mode.value=s.application_mode||'PREPARE';wizardStep=0;showWizardStep();$('#wizard').showModal()};
$('#form').onsubmit=async e=>{e.preventDefault();let f=e.target,c=await api('/api/config'),p=c.profile,s=c.preferences;for(let n of ['name','email','phone','location','work_authorization'])p[n]=f[n].value;p.skills=f.skills.value.split(',').map(x=>x.trim()).filter(Boolean);p.salary_expectations=f.salary.value;s.job_categories=f.categories.value.split(',').map(x=>x.trim()).filter(Boolean);s.priority_locations=f.locations.value.split(',').map(x=>x.trim()).filter(Boolean);s.minimum_score=+f.score.value;s.schedule_times=f.schedule.value.split(',').map(x=>x.trim()).filter(Boolean);s.search_feeds=f.feeds.value.split(/\n/).map(x=>x.trim()).filter(Boolean);s.career_pages=f.career_pages.value.split(/\n/).map(x=>x.trim()).filter(Boolean);s.greenhouse_boards=f.greenhouse.value.split(',').map(x=>x.trim()).filter(Boolean);s.lever_sites=f.lever.value.split(',').map(x=>x.trim()).filter(Boolean);s.application_mode=f.mode.value;await api('/api/setup',json('POST',{profile:p,preferences:s}));if(f.cv.files[0]){let data=new FormData;data.append('file',f.cv.files[0]);await api('/api/cv',{method:'POST',body:data})}$('#wizard').close();notify('Setup saved. Starting the first verified search.');await api('/api/runs',{method:'POST'});$('#progress').classList.remove('hidden');poll();load()};
api('/api/health').then(h=>{document.title=`Tumelo Job Agent ${h.version}`;if(!location.hash)location.hash='dashboard'});

if('serviceWorker' in navigator)navigator.serviceWorker.register('/service-worker.js');

$('#loginForm').onsubmit=async e=>{e.preventDefault();let f=e.target;try{let r=await fetch('/api/auth/login',json('POST',{username:f.username.value,password:f.password.value})),d=await r.json();if(!r.ok)throw Error(d.detail||'Login failed');csrf=d.csrf_token;$('#loginModal').close();notify('Signed in');load()}catch(err){notify(err.message,true)}};api('/api/auth/status').then(s=>{if(s.authenticated){csrf=s.csrf_token;load()}else $('#loginModal').showModal()});

let wizardStep=0;function showWizardStep(){let steps=[...document.querySelectorAll('#form fieldset')];steps.forEach((step,index)=>step.hidden=index!==wizardStep);$('#stepLabel').textContent=`STEP ${wizardStep+1} OF ${steps.length}`;$('#previousStep').style.visibility=wizardStep?'visible':'hidden';$('#nextStep').style.display=wizardStep===steps.length-1?'none':'inline-flex'}$('#nextStep').onclick=()=>{let current=[...document.querySelectorAll('#form fieldset')][wizardStep];if(![...current.querySelectorAll('[required]')].every(input=>input.reportValidity()))return;wizardStep++;showWizardStep()};$('#previousStep').onclick=()=>{wizardStep=Math.max(0,wizardStep-1);showWizardStep()};

$('#form').cv.onchange=async e=>{if(!e.target.files[0])return;let data=new FormData;data.append('file',e.target.files[0]);try{let result=await api('/api/cv',{method:'POST',body:data});$('#cvPreview').textContent=result.parsed_text||'No text could be extracted. Verify the source file.';notify('CV parsed. Review the preview.')}catch(error){notify(error.message,true)}};
