const $=s=>document.querySelector(s), api=(u,o)=>fetch(u,o).then(async r=>{if(!r.ok)throw Error((await r.json()).detail||r.statusText);return r.json()});
const labels={jobs_found:'Jobs found',analyzed:'Analysed',strong_matches:'Strong matches',submitted:'Submitted',manual_pending:'Manual pending',interviews:'Interviews'};
async function load(){let m=await api('/api/overview');$('#metrics').innerHTML=Object.entries(labels).map(([k,v])=>`<div class=metric><b>${m?.[k]||0}</b><span>${v}</span></div>`).join('');let q=encodeURIComponent($('#search').value),s=encodeURIComponent($('#status').value),jobs=await api(`/api/jobs?q=${q}&status=${s}`);$('#empty').style.display=jobs.length?'none':'block';$('#jobrows').innerHTML=jobs.map(j=>`<tr><td><div class=score>${Math.round(j.score||0)}</div></td><td><div class=title>${esc(j.title)}</div><div class=sub>${esc(j.company)} · ${esc(j.classification||'Not analysed')}</div></td><td>${esc(j.location||'Not stated')}</td><td>${esc(j.source)}</td><td><span class=pill>${esc(j.status)}</span></td><td><button onclick="detail(${j.id})">View</button></td></tr>`).join('')}
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function detail(id){let j=await api('/api/jobs/'+id);$('#detail').innerHTML=`<p class=eyebrow>${esc(j.classification||'VACANCY')}</p><h2>${esc(j.title)}</h2><p>${esc(j.company)} · ${esc(j.location)}</p><h3>Match analysis — ${j.score||0}/100</h3><p>${esc(j.reasoning)}</p><p><b>Missing or unverified terms:</b> ${esc(j.missing_requirements)}</p><h3>Description</h3><div class=description>${esc(j.description)}</div><p><b>CV:</b> ${esc(j.cv_path||'Not generated')}<br><b>Cover letter:</b> ${esc(j.cover_letter_path||'Not generated')}</p><div class=actions><button onclick="act(${id},'cv')">Generate CV</button><button onclick="act(${id},'cover-letter')">Cover letter</button><button onclick="status(${id},'READY TO APPLY')">Prepare</button><button onclick="status(${id},'SKIPPED')">Skip</button><button onclick="status(${id},'APPLIED')">Mark applied</button><button onclick="status(${id},'INTERVIEW')">Interview</button><button onclick="status(${id},'REJECTED')">Rejected</button><button onclick="window.open('${esc(j.vacancy_url)}','_blank')">Open job ↗</button></div>`;$('#modal').showModal()}
async function act(id,a){try{await api(`/api/jobs/${id}/${a}`,{method:'POST'});await detail(id);load()}catch(e){alert(e.message)}}async function status(id,s){await api(`/api/jobs/${id}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s})});await detail(id);load()}
$('#run').onclick=async()=>{await api('/api/runs?sample=false',{method:'POST'});$('#progress').classList.remove('hidden');poll()};async function poll(){let r=await api('/api/runs/latest');$('#runmsg').textContent=r.message;$('#runstate').textContent=r.state;if(r.state==='RUNNING')setTimeout(poll,1200);else{setTimeout(()=>$('#progress').classList.add('hidden'),2500);load()}}
$('#search').oninput=load;$('#status').onchange=load;document.querySelectorAll('.close').forEach(x=>x.onclick=()=>x.closest('dialog').close());$('#setup').onclick=async()=>{let c=await api('/api/config'),f=$('#form');f.name.value=c.profile.name||'';f.email.value=c.profile.email||'';f.phone.value=c.profile.phone||'';f.location.value=c.profile.location||'';f.locations.value=(c.preferences.priority_locations||[]).join(', ');f.categories.value=(c.preferences.job_categories||[]).join(', ');f.score.value=c.preferences.minimum_score||75;f.mode.value=c.preferences.application_mode||'PREPARE';$('#wizard').showModal()};
$('#form').onsubmit=async e=>{e.preventDefault();let f=e.target,c=await api('/api/config');Object.assign(c.profile,{name:f.name.value,email:f.email.value,phone:f.phone.value,location:f.location.value});Object.assign(c.preferences,{priority_locations:f.locations.value.split(',').map(x=>x.trim()).filter(Boolean),job_categories:f.categories.value.split(',').map(x=>x.trim()).filter(Boolean),minimum_score:+f.score.value,application_mode:f.mode.value});await api('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:c.profile,preferences:c.preferences})});if(f.cv.files[0]){let d=new FormData;d.append('file',f.cv.files[0]);await api('/api/cv',{method:'POST',body:d})}$('#wizard').close();load()};
api('/api/health').then(h=>{if(!h.cv_loaded)setTimeout(()=>$('#setup').click(),500)});load();
